# Generated by Django 6.0.5 on 2026-05-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'System User', 'verbose_name_plural': 'System Users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='is_default_password',
            field=models.BooleanField(default=True, help_text='Security flag to force password reset on first login.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin/System Owner'), ('MANAGER', 'Business Manager'), ('CHEF', 'Kitchen Controller'), ('WAITER', 'Service Waiter')], db_index=True, default='WAITER', max_length=10),
        ),
    ]
