# Generated by Django 6.0.5 on 2026-05-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_options_remove_order_status_and_more'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-paid_at'], 'verbose_name': 'Financial Transaction', 'verbose_name_plural': 'Financial Transactions'},
        ),
        migrations.RemoveField(
            model_name='payment',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.AddField(
            model_name='payment',
            name='amount_received',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Actual amount handed over by customer.', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='change_given',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='orders',
            field=models.ManyToManyField(help_text='The orders being settled in this transaction.', related_name='payments', to='order.order'),
        ),
        migrations.AddField(
            model_name='payment',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Calculated total from linked orders.', max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'Vodacom M-Pesa'), ('tigopesa', 'Tigo Pesa'), ('airtelmoney', 'Airtel Money'), ('n_card', 'N-Card'), ('halo_pesa', 'Halo Pesa')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Reference ID for Mobile Money or N-Card.', max_length=100, null=True, unique=True),
        ),
    ]
