# Generated by Django 6.0.5 on 2026-05-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['category', 'item_name'], 'verbose_name': 'Menu Item', 'verbose_name_plural': 'Menu Items'},
        ),
        migrations.AddField(
            model_name='menu',
            name='category',
            field=models.CharField(choices=[('FOOD', 'Food'), ('DRINK', 'Drinks'), ('SNACK', 'Snacks/Starters'), ('OTHER', 'Other Services')], default='FOOD', max_length=20),
        ),
        migrations.AddField(
            model_name='menu',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=models.TextField(blank=True, help_text='Ingredients or extra details', null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='item_name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price in TZS', max_digits=10),
        ),
    ]
