# Generated by Django 6.0.4 on 2026-05-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meza', models.CharField(max_length=20)),
                ('chakula', models.CharField(max_length=100)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('muda', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
